#+STARTUP: overview
#+TITLE: HSPC dynamics analysis code repository

This repository contains R and python scripts used to perform analysis published in the Kucinski et al. 2022 paper: "TITLETTLE". *DOI BADGE*

* scRNA-Seq analysis
All the scripts for analysis are located in the main directory.
Script process the data, reproduce figures presented in our article and prepare inputs necessary for the discrete and continous models of HSPC dynamics.

The easiest way to reproduce our scRNA-Seq analysis can is to use our [[https://docs.sylabs.io/guides/3.10/user-guide/][Singularity]] container.
The container contains R and python installations and all necessary packages and can be found here: [[http://128.232.224.252/HSPCdynamics/HSPCdynamics_container.sif][link]]

** How to use
To reproduce the analysis presented in the paper:

1. Clone and enter the repository:
#+begin_src bash
git clone https://github.com/Iwo-K/HSPCdynamics
cd HSPCdynamics
#+end_src
2. Download the [[http://128.232.224.252/HSPCdynamics/HSPCdynamics_container.sif][container]]
3. Modify the container variable in the run_analysis.sh script to point to the singularity image
4. Download the [[http://128.232.224.252/HSPCdynamics/HSPCdynamics_data.tar.gz][initial data]], decompress and move to the directory: HSPCdynamics/data
5. Run the analysis:
 #+begin_src bash
 ./run_analysis.sh
 #+end_src

This script will create several directories to hold output files from respective analysis script, e.g. figures or processed data. Additionally, the .R scripts will be converted into .html reports and .py scripts into Jupyter/IPython notebooks, to allow easy inspection.

* Discrete model

* Continuous
Code uses the pseudodynamics framework devloped by Fabian Theis' lab ([[https://doi.org/10.1038/s41587-019-0088-0][paper]], [[https://github.com/theislab/pseudodynamics][Github]]).
Code requiers a specific versiono of matlab: r2017b and gcc: gcc-4.9.4-gcc-4.8.5-3sdjf2c
works only with these specific versions of matlab (r2017b) and gcc (4.9.4)

Analys is provided in the PD_model directory, each analyse trajectory in a separate subdirectory.
* Note:
In the publication clusters were relabelled with consecutive numbers, this repository uses the original numbers, with the mapping provided below:

#+CAPTION: Cluster name mapping
| python | matlab | original name | publication |
|--------+--------+---------------+-------------|
|      0 |      1 |            0a |          0a |
|      1 |      2 |             1 |           1 |
|      2 |      3 |             2 |           2 |
|      3 |      4 |             3 |           3 |
|      4 |      5 |             4 |           4 |
|      5 |      6 |             5 |           5 |
|      6 |      7 |             6 |           6 |
|      7 |      8 |             7 |           7 |
|      8 |      9 |             8 |           8 |
|      9 |     10 |             9 |           9 |
|     10 |     11 |            10 |          10 |
|     11 |     12 |            11 |          11 |
|     12 |     13 |            12 |          12 |
|     13 |     14 |            14 |          13 |
|     14 |     15 |            16 |          14 |
|     15 |     16 |            20 |          15 |
|     16 |     17 |            24 |          16 |
|     17 |     18 |            25 |          17 |
|     18 |     19 |            26 |          18 |
|     19 |     20 |            28 |          19 |
|     NA |     21 |            0a |          0a |
|     NA |     22 |            0b |          0b |
